apiVersion: v1
kind: Pod
metadata:
  name: node2
  labels:
    run: amazonlinux2
spec:
  #nodeName: ip-172-29-3-10.ec2.internal
  containers:
  - image: amazonlinux:2
    name: amazonlinux2
    command:
      - "sleep"
      - "1000000"
    resources: {}
status: {}
